name: Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: viniciusValentini
          outputs: |
            dist/snake.svg

      - name: Check files
        run: ls -la dist

      - name: Deploy snake
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
